using System.Text;
using System.Text.Json;
using AutoEnvPlus.Core.Runtimes;

namespace AutoEnvPlus.Core.Projects;

public sealed record ImportedRuntimeSelection(
    RuntimeKind Kind,
    VersionSelector Selector,
    string SourcePath,
    string RawValue);

public sealed record ProjectEnvironmentImportResult(
    string? ProjectRoot,
    IReadOnlyDictionary<RuntimeKind, VersionSelector> Selections,
    IReadOnlyList<ImportedRuntimeSelection> Sources,
    IReadOnlyList<string> Warnings)
{
    public bool Found => ProjectRoot is not null && Sources.Count > 0;
}

public sealed class ProjectEnvironmentImportService
{
    private static readonly string[] MarkerFiles =
    [
        ".python-version",
        ".nvmrc",
        ".node-version",
        ".java-version",
        "package.json",
        "global.json",
    ];

    public ProjectEnvironmentImportResult Discover(string startPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(startPath);
        string fullPath = Path.GetFullPath(startPath);
        DirectoryInfo? directory = File.Exists(fullPath)
            ? new FileInfo(fullPath).Directory
            : new DirectoryInfo(fullPath);
        while (directory is not null)
        {
            if (MarkerFiles.Any(file => File.Exists(Path.Combine(directory.FullName, file))))
            {
                return ImportDirectory(directory.FullName);
            }

            directory = directory.Parent;
        }

        return new ProjectEnvironmentImportResult(
            null,
            new Dictionary<RuntimeKind, VersionSelector>(),
            [],
            []);
    }

    public ProjectEnvironmentImportResult ImportDirectory(string projectRoot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(projectRoot);
        string root = Path.GetFullPath(projectRoot);
        Dictionary<RuntimeKind, ImportedRuntimeSelection> selected = [];
        List<ImportedRuntimeSelection> sources = [];
        List<string> warnings = [];

        ImportMarker(
            Path.Combine(root, ".python-version"),
            RuntimeKind.Python,
            selected,
            sources,
            warnings);
        ImportMarker(
            Path.Combine(root, ".nvmrc"),
            RuntimeKind.NodeJs,
            selected,
            sources,
            warnings,
            NormalizeNodeMarker);
        ImportMarker(
            Path.Combine(root, ".node-version"),
            RuntimeKind.NodeJs,
            selected,
            sources,
            warnings,
            NormalizeNodeMarker);
        ImportMarker(
            Path.Combine(root, ".java-version"),
            RuntimeKind.Java,
            selected,
            sources,
            warnings);
        ImportPackageJson(
            Path.Combine(root, "package.json"),
            selected,
            sources,
            warnings);
        ImportDotNetGlobalJson(
            Path.Combine(root, "global.json"),
            selected,
            sources,
            warnings);

        return new ProjectEnvironmentImportResult(
            root,
            selected.ToDictionary(pair => pair.Key, pair => pair.Value.Selector),
            sources,
            warnings);
    }

    public async Task<string> WriteManifestAsync(
        ProjectEnvironmentImportResult import,
        bool overwrite = false,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(import);
        if (!import.Found || import.ProjectRoot is null)
        {
            throw new InvalidOperationException("No project runtime markers were discovered.");
        }

        string manifestPath = Path.Combine(import.ProjectRoot, ProjectManifestService.ManifestFileName);
        if (File.Exists(manifestPath) && !overwrite)
        {
            throw new IOException($"The project already contains {ProjectManifestService.ManifestFileName}.");
        }

        StringBuilder content = new();
        content.AppendLine("# Generated by AutoEnvPlus from existing project version files.");
        content.AppendLine("[tools]");
        foreach ((RuntimeKind kind, VersionSelector selector) in import.Selections.OrderBy(pair => pair.Key))
        {
            content.Append(ToolName(kind));
            content.Append(" = \"");
            content.Append(selector.ToString().Replace("\"", "\\\"", StringComparison.Ordinal));
            content.AppendLine("\"");
        }

        string temporary = manifestPath + $".{Guid.NewGuid():N}.tmp";
        try
        {
            await File.WriteAllTextAsync(
                temporary,
                content.ToString(),
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
                cancellationToken).ConfigureAwait(false);
            File.Move(temporary, manifestPath, overwrite);
            return manifestPath;
        }
        finally
        {
            if (File.Exists(temporary))
            {
                File.Delete(temporary);
            }
        }
    }

    private static void ImportMarker(
        string path,
        RuntimeKind kind,
        Dictionary<RuntimeKind, ImportedRuntimeSelection> selected,
        List<ImportedRuntimeSelection> sources,
        List<string> warnings,
        Func<string, string>? normalize = null)
    {
        if (!File.Exists(path))
        {
            return;
        }

        string? raw = File.ReadLines(path)
            .Select(line => line.Trim())
            .FirstOrDefault(line => line.Length > 0 && !line.StartsWith('#'));
        if (raw is null)
        {
            warnings.Add($"{path} does not contain a version selector.");
            return;
        }

        AddSelection(
            kind,
            raw,
            normalize?.Invoke(raw) ?? raw,
            path,
            selected,
            sources,
            warnings);
    }

    private static void ImportPackageJson(
        string path,
        Dictionary<RuntimeKind, ImportedRuntimeSelection> selected,
        List<ImportedRuntimeSelection> sources,
        List<string> warnings)
    {
        if (!File.Exists(path))
        {
            return;
        }

        try
        {
            using JsonDocument document = JsonDocument.Parse(File.ReadAllBytes(path));
            if (!document.RootElement.TryGetProperty("engines", out JsonElement engines)
                || engines.ValueKind != JsonValueKind.Object
                || !engines.TryGetProperty("node", out JsonElement node)
                || node.ValueKind != JsonValueKind.String
                || node.GetString() is not string raw)
            {
                return;
            }

            if (!TryNormalizePackageRange(raw, out string? normalized))
            {
                warnings.Add(
                    $"{path} declares engines.node='{raw}', which is a compound range and was kept advisory rather than simplified incorrectly.");
                return;
            }

            AddSelection(
                RuntimeKind.NodeJs,
                raw,
                normalized!,
                path + "#engines.node",
                selected,
                sources,
                warnings);
        }
        catch (JsonException exception)
        {
            warnings.Add($"Unable to parse {path}: {exception.Message}");
        }
    }

    private static void ImportDotNetGlobalJson(
        string path,
        Dictionary<RuntimeKind, ImportedRuntimeSelection> selected,
        List<ImportedRuntimeSelection> sources,
        List<string> warnings)
    {
        if (!File.Exists(path))
        {
            return;
        }

        try
        {
            using JsonDocument document = JsonDocument.Parse(File.ReadAllBytes(path));
            if (document.RootElement.TryGetProperty("sdk", out JsonElement sdk)
                && sdk.ValueKind == JsonValueKind.Object
                && sdk.TryGetProperty("version", out JsonElement version)
                && version.ValueKind == JsonValueKind.String
                && version.GetString() is string raw)
            {
                AddSelection(
                    RuntimeKind.DotNet,
                    raw,
                    raw,
                    path + "#sdk.version",
                    selected,
                    sources,
                    warnings);
            }
        }
        catch (JsonException exception)
        {
            warnings.Add($"Unable to parse {path}: {exception.Message}");
        }
    }

    private static void AddSelection(
        RuntimeKind kind,
        string raw,
        string normalized,
        string sourcePath,
        Dictionary<RuntimeKind, ImportedRuntimeSelection> selected,
        List<ImportedRuntimeSelection> sources,
        List<string> warnings)
    {
        if (!VersionSelector.TryParse(normalized, out VersionSelector? selector))
        {
            warnings.Add($"{sourcePath} contains unsupported selector '{raw}'.");
            return;
        }

        ImportedRuntimeSelection candidate = new(kind, selector!, sourcePath, raw);
        sources.Add(candidate);
        if (selected.TryGetValue(kind, out ImportedRuntimeSelection? existing))
        {
            if (existing.Selector != candidate.Selector)
            {
                warnings.Add(
                    $"{sourcePath} requests {kind} {candidate.Selector}, but higher-priority {existing.SourcePath} requests {existing.Selector}; keeping {existing.Selector}.");
            }

            return;
        }

        selected[kind] = candidate;
    }

    private static string NormalizeNodeMarker(string value)
    {
        string normalized = value.Trim();
        if (normalized.Equals("node", StringComparison.OrdinalIgnoreCase))
        {
            return "latest";
        }

        if (normalized.Equals("lts/*", StringComparison.OrdinalIgnoreCase)
            || normalized.Equals("lts", StringComparison.OrdinalIgnoreCase))
        {
            return "lts";
        }

        return normalized;
    }

    private static bool TryNormalizePackageRange(string value, out string? normalized)
    {
        normalized = value.Trim();
        if (VersionSelector.TryParse(normalized, out _))
        {
            return true;
        }

        if (normalized.Contains("||", StringComparison.Ordinal)
            || normalized.Contains(' ')
            || normalized.StartsWith('>')
            || normalized.StartsWith('<'))
        {
            normalized = null;
            return false;
        }

        if (normalized.StartsWith('^'))
        {
            string version = normalized[1..];
            if (RuntimeVersion.TryParse(version, out RuntimeVersion? parsed))
            {
                if (parsed!.Minor == 0 && parsed.Patch == 0 && parsed.Revision == 0)
                {
                    normalized = parsed.Major.ToString(System.Globalization.CultureInfo.InvariantCulture);
                    return true;
                }

                normalized = null;
                return false;
            }
        }

        if (normalized.StartsWith('~'))
        {
            string version = normalized[1..];
            if (RuntimeVersion.TryParse(version, out RuntimeVersion? parsed))
            {
                if (parsed!.Patch == 0 && parsed.Revision == 0)
                {
                    normalized = $"{parsed.Major}.{parsed.Minor}";
                    return true;
                }

                normalized = null;
                return false;
            }
        }

        string wildcard = normalized
            .Replace(".x", string.Empty, StringComparison.OrdinalIgnoreCase)
            .Replace(".*", string.Empty, StringComparison.OrdinalIgnoreCase);
        if (VersionSelector.TryParse(wildcard, out _))
        {
            normalized = wildcard;
            return true;
        }

        normalized = null;
        return false;
    }

    private static string ToolName(RuntimeKind kind) => kind switch
    {
        RuntimeKind.NodeJs => "node",
        RuntimeKind.DotNet => "dotnet",
        _ => kind.ToString().ToLowerInvariant(),
    };
}
